/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplicantSubmitTransactionDataRequest1Applicant;
import com.konfigthis.client.model.ApplicantSubmitTransactionDataRequest1Counterparty;
import com.konfigthis.client.model.ApplicantSubmitTransactionDataRequest1Props;
import com.konfigthis.client.model.ApplicantSubmitTransactionDataRequestInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantSubmitTransactionDataRequest1
 */
public class ApplicantSubmitTransactionDataRequest1Test {
    private final ApplicantSubmitTransactionDataRequest1 model = new ApplicantSubmitTransactionDataRequest1();

    /**
     * Model tests for ApplicantSubmitTransactionDataRequest1
     */
    @Test
    public void testApplicantSubmitTransactionDataRequest1() {
        // TODO: test ApplicantSubmitTransactionDataRequest1
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

    /**
     * Test the property 'txnId'
     */
    @Test
    public void txnIdTest() {
        // TODO: test txnId
    }

    /**
     * Test the property 'txnDate'
     */
    @Test
    public void txnDateTest() {
        // TODO: test txnDate
    }

    /**
     * Test the property 'applicant'
     */
    @Test
    public void applicantTest() {
        // TODO: test applicant
    }

    /**
     * Test the property 'counterparty'
     */
    @Test
    public void counterpartyTest() {
        // TODO: test counterparty
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'sourceKey'
     */
    @Test
    public void sourceKeyTest() {
        // TODO: test sourceKey
    }

    /**
     * Test the property 'props'
     */
    @Test
    public void propsTest() {
        // TODO: test props
    }

}
