/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantSubmitTransactionDataRequestInfo
 */
public class ApplicantSubmitTransactionDataRequestInfoTest {
    private final ApplicantSubmitTransactionDataRequestInfo model = new ApplicantSubmitTransactionDataRequestInfo();

    /**
     * Model tests for ApplicantSubmitTransactionDataRequestInfo
     */
    @Test
    public void testApplicantSubmitTransactionDataRequestInfo() {
        // TODO: test ApplicantSubmitTransactionDataRequestInfo
    }

    /**
     * Test the property 'direction'
     */
    @Test
    public void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'amountInDefaultCurrency'
     */
    @Test
    public void amountInDefaultCurrencyTest() {
        // TODO: test amountInDefaultCurrency
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'cryptoChain'
     */
    @Test
    public void cryptoChainTest() {
        // TODO: test cryptoChain
    }

    /**
     * Test the property 'paymentTxnId'
     */
    @Test
    public void paymentTxnIdTest() {
        // TODO: test paymentTxnId
    }

    /**
     * Test the property 'paymentDetails'
     */
    @Test
    public void paymentDetailsTest() {
        // TODO: test paymentDetails
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
