/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplicantCreatePaymentSourceActionsResponsePaymentSource;
import com.konfigthis.client.model.ApplicantCreatePaymentSourceActionsResponseRequiredIdDocs;
import com.konfigthis.client.model.ApplicantCreatePaymentSourceActionsResponseReview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantCreatePaymentSourceActionsResponse
 */
public class ApplicantCreatePaymentSourceActionsResponseTest {
    private final ApplicantCreatePaymentSourceActionsResponse model = new ApplicantCreatePaymentSourceActionsResponse();

    /**
     * Model tests for ApplicantCreatePaymentSourceActionsResponse
     */
    @Test
    public void testApplicantCreatePaymentSourceActionsResponse() {
        // TODO: test ApplicantCreatePaymentSourceActionsResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'externalActionId'
     */
    @Test
    public void externalActionIdTest() {
        // TODO: test externalActionId
    }

    /**
     * Test the property 'applicantId'
     */
    @Test
    public void applicantIdTest() {
        // TODO: test applicantId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'review'
     */
    @Test
    public void reviewTest() {
        // TODO: test review
    }

    /**
     * Test the property 'requiredIdDocs'
     */
    @Test
    public void requiredIdDocsTest() {
        // TODO: test requiredIdDocs
    }

    /**
     * Test the property 'paymentSource'
     */
    @Test
    public void paymentSourceTest() {
        // TODO: test paymentSource
    }

}
