/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantCreatePaymentSourceActionsResponseReview
 */
public class ApplicantCreatePaymentSourceActionsResponseReviewTest {
    private final ApplicantCreatePaymentSourceActionsResponseReview model = new ApplicantCreatePaymentSourceActionsResponseReview();

    /**
     * Model tests for ApplicantCreatePaymentSourceActionsResponseReview
     */
    @Test
    public void testApplicantCreatePaymentSourceActionsResponseReview() {
        // TODO: test ApplicantCreatePaymentSourceActionsResponseReview
    }

    /**
     * Test the property 'reviewId'
     */
    @Test
    public void reviewIdTest() {
        // TODO: test reviewId
    }

    /**
     * Test the property 'attemptId'
     */
    @Test
    public void attemptIdTest() {
        // TODO: test attemptId
    }

    /**
     * Test the property 'attemptCnt'
     */
    @Test
    public void attemptCntTest() {
        // TODO: test attemptCnt
    }

    /**
     * Test the property 'levelName'
     */
    @Test
    public void levelNameTest() {
        // TODO: test levelName
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'reviewStatus'
     */
    @Test
    public void reviewStatusTest() {
        // TODO: test reviewStatus
    }

}
