/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplicantImportCompletedRequestInfo;
import com.konfigthis.client.model.ApplicantImportCompletedRequestReview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantImportCompletedRequest
 */
public class ApplicantImportCompletedRequestTest {
    private final ApplicantImportCompletedRequest model = new ApplicantImportCompletedRequest();

    /**
     * Model tests for ApplicantImportCompletedRequest
     */
    @Test
    public void testApplicantImportCompletedRequest() {
        // TODO: test ApplicantImportCompletedRequest
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

    /**
     * Test the property 'externalUserId'
     */
    @Test
    public void externalUserIdTest() {
        // TODO: test externalUserId
    }

    /**
     * Test the property 'review'
     */
    @Test
    public void reviewTest() {
        // TODO: test review
    }

}
