/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo
 */
public class ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfoTest {
    private final ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo model = new ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo();

    /**
     * Model tests for ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo
     */
    @Test
    public void testApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo() {
        // TODO: test ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo
    }

    /**
     * Test the property 'accountIdentifier'
     */
    @Test
    public void accountIdentifierTest() {
        // TODO: test accountIdentifier
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'institutionName'
     */
    @Test
    public void institutionNameTest() {
        // TODO: test institutionName
    }

}
