/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo
 */
public class ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfoTest {
    private final ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo model = new ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo();

    /**
     * Model tests for ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo
     */
    @Test
    public void testApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo() {
        // TODO: test ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo
    }

    /**
     * Test the property 'lat'
     */
    @Test
    public void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property 'lon'
     */
    @Test
    public void lonTest() {
        // TODO: test lon
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'countryCode3'
     */
    @Test
    public void countryCode3Test() {
        // TODO: test countryCode3
    }

    /**
     * Test the property 'asn'
     */
    @Test
    public void asnTest() {
        // TODO: test asn
    }

    /**
     * Test the property 'asnOrg'
     */
    @Test
    public void asnOrgTest() {
        // TODO: test asnOrg
    }

    /**
     * Test the property 'riskyAsn'
     */
    @Test
    public void riskyAsnTest() {
        // TODO: test riskyAsn
    }

}
