/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplicantAddBeneficiaryRequestApplicant;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantAddBeneficiaryRequest1
 */
public class ApplicantAddBeneficiaryRequest1Test {
    private final ApplicantAddBeneficiaryRequest1 model = new ApplicantAddBeneficiaryRequest1();

    /**
     * Model tests for ApplicantAddBeneficiaryRequest1
     */
    @Test
    public void testApplicantAddBeneficiaryRequest1() {
        // TODO: test ApplicantAddBeneficiaryRequest1
    }

    /**
     * Test the property 'applicant'
     */
    @Test
    public void applicantTest() {
        // TODO: test applicant
    }

    /**
     * Test the property 'applicantId'
     */
    @Test
    public void applicantIdTest() {
        // TODO: test applicantId
    }

    /**
     * Test the property 'positions'
     */
    @Test
    public void positionsTest() {
        // TODO: test positions
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
