/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicantChangeCompanyDataRequest1
 */
public class ApplicantChangeCompanyDataRequest1Test {
    private final ApplicantChangeCompanyDataRequest1 model = new ApplicantChangeCompanyDataRequest1();

    /**
     * Model tests for ApplicantChangeCompanyDataRequest1
     */
    @Test
    public void testApplicantChangeCompanyDataRequest1() {
        // TODO: test ApplicantChangeCompanyDataRequest1
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'registrationNumber'
     */
    @Test
    public void registrationNumberTest() {
        // TODO: test registrationNumber
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'legalAddress'
     */
    @Test
    public void legalAddressTest() {
        // TODO: test legalAddress
    }

    /**
     * Test the property 'incorporatedOn'
     */
    @Test
    public void incorporatedOnTest() {
        // TODO: test incorporatedOn
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'controlScheme'
     */
    @Test
    public void controlSchemeTest() {
        // TODO: test controlScheme
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'taxId'
     */
    @Test
    public void taxIdTest() {
        // TODO: test taxId
    }

    /**
     * Test the property 'registrationLocation'
     */
    @Test
    public void registrationLocationTest() {
        // TODO: test registrationLocation
    }

    /**
     * Test the property 'website'
     */
    @Test
    public void websiteTest() {
        // TODO: test website
    }

    /**
     * Test the property 'postalAddress'
     */
    @Test
    public void postalAddressTest() {
        // TODO: test postalAddress
    }

    /**
     * Test the property 'beneficiaries'
     */
    @Test
    public void beneficiariesTest() {
        // TODO: test beneficiaries
    }

    /**
     * Test the property 'addresses'
     */
    @Test
    public void addressesTest() {
        // TODO: test addresses
    }

}
