/*
 * Sumsub API
 * Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.  Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApplicantImportCompletedRequestReviewReview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Review results
 */
@ApiModel(description = "Review results")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ApplicantImportCompletedRequestReview {
  public static final String SERIALIZED_NAME_CREATE_DATE = "createDate";
  @SerializedName(SERIALIZED_NAME_CREATE_DATE)
  private String createDate;

  public static final String SERIALIZED_NAME_REVIEW_DATE = "reviewDate";
  @SerializedName(SERIALIZED_NAME_REVIEW_DATE)
  private String reviewDate;

  public static final String SERIALIZED_NAME_REVIEW = "review";
  @SerializedName(SERIALIZED_NAME_REVIEW)
  private ApplicantImportCompletedRequestReviewReview review;

  public static final String SERIALIZED_NAME_REVIEW_STATUS = "reviewStatus";
  @SerializedName(SERIALIZED_NAME_REVIEW_STATUS)
  private String reviewStatus;

  public ApplicantImportCompletedRequestReview() {
  }

  public ApplicantImportCompletedRequestReview createDate(String createDate) {
    
    
    
    
    this.createDate = createDate;
    return this;
  }

   /**
   * Date of users&#39; creation on your side in a format: \&quot;2022-11-21 08:25:32+0000\&quot;
   * @return createDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date of users' creation on your side in a format: \"2022-11-21 08:25:32+0000\"")

  public String getCreateDate() {
    return createDate;
  }


  public void setCreateDate(String createDate) {
    
    
    
    this.createDate = createDate;
  }


  public ApplicantImportCompletedRequestReview reviewDate(String reviewDate) {
    
    
    
    
    this.reviewDate = reviewDate;
    return this;
  }

   /**
   * review date on your side in a format: \&quot;2022-11-21 08:25:32+0000\&quot;
   * @return reviewDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "review date on your side in a format: \"2022-11-21 08:25:32+0000\"")

  public String getReviewDate() {
    return reviewDate;
  }


  public void setReviewDate(String reviewDate) {
    
    
    
    this.reviewDate = reviewDate;
  }


  public ApplicantImportCompletedRequestReview review(ApplicantImportCompletedRequestReviewReview review) {
    
    
    
    
    this.review = review;
    return this;
  }

   /**
   * Get review
   * @return review
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ApplicantImportCompletedRequestReviewReview getReview() {
    return review;
  }


  public void setReview(ApplicantImportCompletedRequestReviewReview review) {
    
    
    
    this.review = review;
  }


  public ApplicantImportCompletedRequestReview reviewStatus(String reviewStatus) {
    
    
    
    
    this.reviewStatus = reviewStatus;
    return this;
  }

   /**
   * \&quot;completed\&quot;
   * @return reviewStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "\"completed\"")

  public String getReviewStatus() {
    return reviewStatus;
  }


  public void setReviewStatus(String reviewStatus) {
    
    
    
    this.reviewStatus = reviewStatus;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ApplicantImportCompletedRequestReview instance itself
   */
  public ApplicantImportCompletedRequestReview putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicantImportCompletedRequestReview applicantImportCompletedRequestReview = (ApplicantImportCompletedRequestReview) o;
    return Objects.equals(this.createDate, applicantImportCompletedRequestReview.createDate) &&
        Objects.equals(this.reviewDate, applicantImportCompletedRequestReview.reviewDate) &&
        Objects.equals(this.review, applicantImportCompletedRequestReview.review) &&
        Objects.equals(this.reviewStatus, applicantImportCompletedRequestReview.reviewStatus)&&
        Objects.equals(this.additionalProperties, applicantImportCompletedRequestReview.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createDate, reviewDate, review, reviewStatus, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicantImportCompletedRequestReview {\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    reviewDate: ").append(toIndentedString(reviewDate)).append("\n");
    sb.append("    review: ").append(toIndentedString(review)).append("\n");
    sb.append("    reviewStatus: ").append(toIndentedString(reviewStatus)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("createDate");
    openapiFields.add("reviewDate");
    openapiFields.add("review");
    openapiFields.add("reviewStatus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ApplicantImportCompletedRequestReview
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ApplicantImportCompletedRequestReview.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApplicantImportCompletedRequestReview is not found in the empty JSON string", ApplicantImportCompletedRequestReview.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("createDate") != null && !jsonObj.get("createDate").isJsonNull()) && !jsonObj.get("createDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createDate").toString()));
      }
      if ((jsonObj.get("reviewDate") != null && !jsonObj.get("reviewDate").isJsonNull()) && !jsonObj.get("reviewDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reviewDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reviewDate").toString()));
      }
      // validate the optional field `review`
      if (jsonObj.get("review") != null && !jsonObj.get("review").isJsonNull()) {
        ApplicantImportCompletedRequestReviewReview.validateJsonObject(jsonObj.getAsJsonObject("review"));
      }
      if ((jsonObj.get("reviewStatus") != null && !jsonObj.get("reviewStatus").isJsonNull()) && !jsonObj.get("reviewStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reviewStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reviewStatus").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApplicantImportCompletedRequestReview.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApplicantImportCompletedRequestReview' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApplicantImportCompletedRequestReview> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApplicantImportCompletedRequestReview.class));

       return (TypeAdapter<T>) new TypeAdapter<ApplicantImportCompletedRequestReview>() {
           @Override
           public void write(JsonWriter out, ApplicantImportCompletedRequestReview value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ApplicantImportCompletedRequestReview read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ApplicantImportCompletedRequestReview instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ApplicantImportCompletedRequestReview given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ApplicantImportCompletedRequestReview
  * @throws IOException if the JSON string is invalid with respect to ApplicantImportCompletedRequestReview
  */
  public static ApplicantImportCompletedRequestReview fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApplicantImportCompletedRequestReview.class);
  }

 /**
  * Convert an instance of ApplicantImportCompletedRequestReview to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

